stages:
  - build
#  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/frontend
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA 
  #CI_DEBUG_TRACE: "true"          

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache openssh-client ansible  
  script:
    - mkdir -p ~/.ssh
    - echo "$DEPOLY_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - chmod 700 ~/.ssh
    - ansible-playbook -i ansible/inventory/hosts.yml ansible/playbook.yml
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
