stages:
  - build
  - test
  - deploy

variables:
  APP_ENV: production

build_job:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  cache:
    paths:
    - node_modules/

test_job:
  stage: test
  script:
    - npm run test