workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev-frontend"'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build
#  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/frontend
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - frontend/node_modules/

build-:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG frontend/
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      when: always
      changes: [ "frontend/**/*" ]
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev-frontend"'
      changes: [ "frontend/**/*" ]


deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client ansible
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 10.10.146.218 >> ~/.ssh/known_hosts
  script:
    - ansible-playbook -i frontend/ansible/inventory/hosts.yml --extra-vars "docker_image=$DOCKER_IMAGE tag=$DOCKER_TAG" frontend/ansible/playbook.yml

  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      when: always
      changes: [ "frontend/**/*" ]
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev-frontend"'
      changes: [ "frontend/**/*" ]