version: '3.8'

services:
  frontend:
    image: ${FRONTEND_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${API_URL}
    volumes:
      - ./logs:/app/logs