stages:
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/group/project/backend

build_backend:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME

deploy_backend:
  stage: deploy
  when: manual
  script:
    - ansible-playbook -i ../infra/inventory.ini ../infra/playbooks/deploy.yml -e "target_env=$CI_COMMIT_REF_NAME"
