server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
  secret: ${JWT_SECRET}
  expireTimeMs: ${JWT_EXPIRATION_MS}
jwt:
  refreshExpirationMs: ${REFRESH_TOKEN_EXPIRATION_MS}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always