server:
  port: 8080
#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
spring:
  cloud:
    gateway:
      routes:
        - id: storage-module
          uri: http://storage-module:8081  # URL микросервиса
          predicates:
            - Path=/storages/**, /objects/**, /units/**, /templates/**

        - id: qr-module
          uri: http://qr-module:8082  # URL микросервиса
          predicates:
              - Path=/qr/**