---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  notify: Restart Nginx

- name: Ensure Nginx config directory exists
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'

- name: Copy main Nginx config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: '0644'
  notify: Restart Nginx

- name: Copy backend Nginx config
  template:
    src: "../backend/templates/nginx-backend.conf.j2"
    dest: "/etc/nginx/conf.d/backend.conf"
    mode: '0644'
  notify: Restart Nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
