---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  notify: Restart Nginx

- name: Ensure Nginx config directory exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'

- name: Copy main Nginx config
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: '0644'
  notify: Restart Nginx

- name: Copy backend vhost
  ansible.builtin.template:
    src: "backend.conf.j2"
    dest: "{{ nginx_conf_path }}"
    mode: '0644'
  notify: Restart Nginx

- name: Ensure Nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
