# Docker / Compose
project_name: "team29-backend"
deploy_root: "/home/team_user/29/backend"   
compose_dir: "{{ deploy_root }}"
compose_file: "docker-compose.yml"

# Контейнеры / порты
container_port: 8080
host_port: 8080

# Nginx
nginx_conf_path: "/etc/nginx/conf.d/backend.conf"
nginx_listen_port: 80
proxy_upstream: "http://127.0.0.1:8080"    # куда проксировать (host-port api-gateway)

# Registry из окружения CI (fallback пустой)
ci_registry: "{{ lookup('env','CI_REGISTRY') | default('', true) }}"
ci_registry_user: "{{ lookup('env','CI_REGISTRY_USER') | default('', true) }}"
ci_registry_password: "{{ lookup('env','CI_REGISTRY_PASSWORD') | default('', true) }}"
image_tag: "{{ lookup('env','CI_COMMIT_SHORT_SHA') | default('latest', true) }}"

backend_repo: "git@it-camp.innoca.local:t1-camp-29/backend.git"
backend_branch: "main"

# Системные пользователи
app_user: "team_user"
app_group: "team_user"
