---
- hosts: frontend
  become: yes
  vars:
    frontend_image: "{{ CI_REGISTRY_IMAGE }}/frontend:{{ CI_COMMIT_SHORT_SHA }}"
    deploy_dir: "/home/team_user/frontend"

  tasks:
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Create deployment directory
      file:
        path: "{{ deploy_dir }}"
        state: directory
        owner: team_user
        group: team_user

    - name: Copy Docker Compose file
      copy:
        src: "docker-compose.prod.yml"
        dest: "{{ deploy_dir }}/docker-compose.prod.yml"
        owner: team_user
        group: team_user

    - name: Login to Docker registry
      community.docker.docker_login:
        registry_url: "{{ CI_REGISTRY }}"
        username: "{{ CI_REGISTRY_USER }}"
        password: "{{ CI_REGISTRY_PASSWORD }}"

    - name: Deploy frontend
      community.docker.docker_compose:
        project_src: "{{ deploy_dir }}"
        files:
          - "{{ deploy_dir }}/docker-compose.prod.yml"
        state: present
        pull: yes
        restart: yes