---
- name: Install required packages
  become: yes
  apt:
    name:
      - docker.io
      - docker-compose
      - rsync
    state: present
    update_cache: yes

- name: Ensure deployment directory exists
  file:
    path: "{{ deploy_dir }}"
    state: directory
    owner: team_user
    group: team_user
    mode: 0755

- name: Synchronize project files with proper permissions
  synchronize:
    src: "{{ playbook_dir }}/../../../frontend/"
    dest: "{{ deploy_dir }}"
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=node_modules"
      - "--chown=team_user:team_user"
    delete: yes
    recursive: yes

- name: Ensure .env file exists
  file:
    path: "{{ deploy_dir }}/.env"
    state: touch
    owner: team_user
    group: team_user
    mode: 0640

- name: Build Docker image
  docker_image:
    name: "{{ docker_image_name }}"
    build:
      path: "{{ deploy_dir }}"
      dockerfile: "{{ deploy_dir }}/Dockerfile"
    source: build
    force_source: yes
    pull: yes

- name: Ensure container is running
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_name }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ host_port }}:{{ container_port }}"
    env_file: "{{ deploy_dir }}/.env"
    volumes:
      - "{{ deploy_dir }}/logs:/app/logs"