---
- name: Install Docker
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Synchronize project files
  synchronize:
    src: "{{ playbook_dir }}/../../../frontend/"
    dest: "{{ deploy_dir }}"
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=node_modules"
    delete: yes 

- name: Build Docker image
  docker_image:
    name: "{{ docker_image_name }}"
    build:
      path: "{{ deploy_dir }}"
      dockerfile: "{{ deploy_dir }}/Dockerfile"
    source: build
    force_source: yes

- name: Run container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_name }}"
    ports:
      - "{{ host_port }}:{{ container_port }}"
    env_file: "{{ deploy_dir }}/.env"
    restart_policy: unless-stopped
