- name: Install required packages
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes
  become: true

- name: Login to Registry
  community.docker.docker_login:
    registry_url: "{{ registry_url }}"
    username: "{{ registry_user }}"
    password: "{{ registry_password }}"

- name: Pull image
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
    source: pull

- name: Ensure .env file exists
  file:
    path: "{{ deploy_dir }}/.env"
    state: touch
    owner: team_user
    group: team_user
    mode: 0640

- name: Run container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_name }}:{{ docker_image_tag }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ host_port }}:{{ container_port }}"
    env_file: "{{ deploy_dir }}/.env"
    volumes:
      - "{{ deploy_dir }}/logs:/app/logs"
