---

- name: Install Docker and Docker Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes


- name: Login to registry
  community.docker.docker_login:
    registry_url: "{{ lookup('env','CI_REGISTRY') }}"
    username: "{{ lookup('env','CI_REGISTRY_USER') }}"
    password: "{{ lookup('env','CI_REGISTRY_PASSWORD') }}"

- name: Pull frontend image
  community.docker.docker_image:
    name: "{{ docker_image }}"
    tag: "{{ tag }}"
    source: pull

- name: Stop existing container
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: absent
  ignore_errors: yes

- name: Run frontend container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image }}:{{ tag }}"
    ports:
      - "{{ host_port }}:{{ container_port }}"
    restart_policy: unless-stopped
