---
- name: Install Docker
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Clone repository
  git:
    repo: '{{ frontend_repo }}'
    dest: '{{ deploy_dir }}'
    version: '{{ frontend_branch }}'
    force: yes
  environment:
    GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no -i /home/team_user/.ssh/id_rsa'

- name: Build Docker image
  docker_image:
    name: '{{ docker_image_name }}'
    build:
      path: '{{ deploy_dir }}'
      dockerfile: '{{ deploy_dir }}/Dockerfile'
    source: build
    force_source: yes

- name: Run container
  docker_container:
    name: '{{ container_name }}'
    image: '{{ docker_image_name }}'
    ports:
      - '{{ host_port }}:{{ container_port }}'
    env_file: '{{ deploy_dir }}/.env'
    restart_policy: unless-stopped
