version: '3.8'

services:
  api-gateway:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - storage-app
      - qr-module
    networks:
      - app-network

  storage-app:  # Должно совпадать с именем в URI
    build: ../storage-module
    ports:
      - "8082:8082"
    networks:
      - app-network
    env_file:
      - ../storage-module/.env

  qr-module:
    build: ../qr-module
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge