all:
  hosts:
    backend:
      ansible_host: "10.10.146.218"
      ansible_user: "team_user"
      ansible_ssh_private_key_file: "~/.ssh/id_rsa"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      ansible_become: true
      ansible_become_method: sudo
      ansible_python_interpreter: /usr/bin/python3
