server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:5173'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - '*'
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth-service
          uri: http://auth-service:8083
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: storage-module
          uri: http://storage-app:8082
          predicates:
            - Path=/api/storages/**, /api/objects/**, /api/units/**, /api/templates/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: qr-module
          uri: http://qr-module:8081
          predicates:
            - Path=/api/qr/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: test-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/test/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: n123aa4d89abcdef01c3bb6789ab1c3bb6789abcdefxyz9876b1c3bb6789ab
