---
- name: Deploy backend stack
  hosts: backend
  become: true
  gather_facts: yes

  pre_tasks:
    - name: Ensure base packages present
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Ensure deploy directory exists with owner
      ansible.builtin.file:
        path: "{{ compose_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0755"

  roles:
    - role: nginx

  tasks:
    - name: Render deploy docker-compose from template
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/docker-compose.deploy.yml.j2"
        dest: "{{ compose_dir }}/docker-compose.yml"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0644"
      vars:
        registry: "{{ registry | default(ci_registry, true) }}"
        tag: "{{ tag | default(image_tag, true) }}"

    # Копируем .env файлы, если они есть в репозитории
    - name: Stat env files in repo
      ansible.builtin.stat:
        path: "{{ item }}"
      register: env_stats
      loop:
        - "{{ playbook_dir }}/../auth-service/.env"
        - "{{ playbook_dir }}/../storage-module/.env"

    - name: Copy env files next to compose
      ansible.builtin.copy:
        src: "{{ item.stat.path }}"
        dest: "{{ compose_dir }}/{{ (item.stat.path | basename).replace('.env','') }}.env"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0600"
      loop: "{{ env_stats.results }}"
      when: item.stat.exists

    - name: Login to container registry
      community.docker.docker_login:
        registry_url: "{{ ci_registry }}"
        username: "{{ ci_registry_user }}"
        password: "{{ ci_registry_password }}"
      when: ci_registry != ""

    - name: Pull images as per compose
      community.docker.docker_compose:
        project_name: "{{ project_name }}"
        project_src: "{{ compose_dir }}"
        files:
          - "docker-compose.yml"
        pull: yes

    - name: Deploy/Update containers
      community.docker.docker_compose:
        project_name: "{{ project_name }}"
        project_src: "{{ compose_dir }}"
        files:
          - "docker-compose.yml"
        state: present

