---
- hosts: backend
  gather_facts: no
  vars:
    compose_dir: "/home/team_user/29/backend"
  tasks:

    - name: Ensure deployment directory exists
      file:
        path: "{{ compose_dir }}"
        state: directory

    - name: Copy docker-compose file
      copy:
        src: "{{ playbook_dir }}/../docker-compose.yml"
        dest: "{{ compose_dir }}/docker-compose.yml"

    - name: Login to registry
      community.docker.docker_login:
        registry_url: "{{ lookup('env','CI_REGISTRY') }}"
        username: "{{ lookup('env','CI_REGISTRY_USER') }}"
        password: "{{ lookup('env','CI_REGISTRY_PASSWORD') }}"

    - name: Pull images according to compose
      community.docker.docker_compose:
        project_src: "{{ compose_dir }}"
        pull: yes

    - name: Deploy containers
      community.docker.docker_compose:
        project_src: "{{ compose_dir }}"
        state: present
